const menuData = [
  {
    id: 1,
    title: "Consulting",
    path: "/consulting",
    newTab: false,
    submenu: [
      {
        id: 111,
        title: "CRM Marketing Strategy",
        path: "/crm-marketing-strategy",
        newTab: false,
        desc: "Boost customer engagement and drive growth with a CRM marketing strategy",
        imglink: "/assets/images/consulting/crm-marketing-strategy.png",
      },
      {
        id: 112,
        title: "CRM Sales Strategy",
        path: "/crm-sales-strategy",
        newTab: false,
        desc: "Boost customer engagement and drive growth with a CRM marketing strategy",
        imglink: "/assets/images/consulting/crm-sales-strategy.png",
      },
      {
        id: 113,
        title: "CRM Customer Service Strategy",
        path: "/crm-customer-service-strategy",
        newTab: false,
        desc: "Elevate customer service using CRM solutions for streamlined operations and support.",
        imglink: "/assets/images/consulting/crm-customer-service-strategy.png",
      },
      {
        id: 114,
        title: "CRM AI Adoption Strategy",
        path: "/crm-ai-adoption-strategy",
        newTab: false,
        desc: "Transform CRM with AI to automate tasks and personalize customer experiences.",
        imglink: "/assets/images/consulting/crm-ai-adoption-strategy.png",
      },
      {
        id: 115,
        title: "CRM Growth Framework",
        path: "/crm-growth-framework",
        newTab: false,
        desc: "Unlock growth by aligning CRM strategies with business objectives for efficiency.",
        imglink: "/assets/images/consulting/crm-growth-framework.png",
      },
      {
        id: 116,
        title: "CRM Right Fitment Planning",
        path: "/crm-right-fitment-planning",
        newTab: false,
        desc: "Customize your CRM solution to align with your business needs for optimal results.",
        imglink: "/assets/images/consulting/crm-right-fitment-planning.png",
      },
      {
        id: 117,
        title: "CRM Audit and Technical Debt Optimization",
        path: "/crm-audit-and-technical-debt-optimization",
        newTab: false,
        desc: "Optimize your CRM system to reduce costs while maximizing performance and ROI.",
        imglink:
          "/assets/images/consulting/crm-audit-and-technical-debt-optimization.png",
      },
      {
        id: 118,
        title: "CRM Customer Communities",
        path: "/crm-customer-communities",
        newTab: false,
        desc: "Foster engagement by building CRM-powered customer communities for deeper connections.",
        imglink: "/assets/images/consulting/crm-customer-communities.png",
      },
      {
        id: 119,
        title: "CRM E-Commerce",
        path: "/crm-e-commerce",
        newTab: false,
        desc: "Streamline e-commerce operations, enhance customer engagement, and drive growth with tailored CRM solutions.",
        imglink: "/assets/images/consulting/crm-e-commerce.png",
      },
      {
        id: 120,
        title: "CRM Program Management",
        path: "/crm-program-management",
        newTab: false,
        desc: "Streamline CRM processes to drive better customer experiences and business growth.",
        imglink: "/assets/images/consulting/crm-program-management.png",
      },
      {
        id: 121,
        title: "CRM Implementation and Integration",
        path: "/crm-implementation-and-integration",
        newTab: false,
        desc: "Seamlessly integrate CRM systems with existing platforms to optimize operations.",
        imglink:
          "/assets/images/consulting/crm-implementation-and-integration.png",
      },
      {
        id: 122,
        title: "Organization-wide Multiple CRM Unification",
        path: "/organization-wide-multiple-crm-unification",
        newTab: false,
        desc: "Unify CRM systems to centralize data and improve organizational efficiency.",
        imglink:
          "/assets/images/consulting/organization-wide-multiple-crm-unification.png",
      },
      {
        id: 123,
        title: "CRM Security Planning",
        path: "/crm-security-planning",
        newTab: false,
        desc: "Secure your CRM journey with advanced protection for data, customers, and business growth",
        imglink: "/assets/images/consulting/crm-security-planning.png",
      },
      {
        id: 124,
        title: "Customer Success Strategy",
        path: "/customer-success-strategy",
        newTab: false,
        desc: "Drive customer success by proactively addressing needs and minimizing churn.",
        imglink: "/assets/images/consulting/customer-success-strategy.png",
      },
    ],
  },
  {
    id: 2,
    title: "Tech Services",
    path: "/tech-services",
    newTab: false,
    submenu: [
      {
        id: 200,
        title: "Salesforce CRM",
        path: "/salesforce-crm",
        newTab: false,
        desc: "Transform your business with strategic Salesforce CRM solutions.",
        imglink: "/assets/images/tech-services/tech-service-1.png",
      },
      {
        id: 202,
        title: "MS Dynamics CRM",
        path: "/ms-dynamics-crm",
        newTab: false,
        desc: "Simplify processes and maximize results with Microsoft Dynamics expertise.",
        imglink: "/assets/images/tech-services/tech-service-2.png",
      },
      {
        id: 204,
        title: "ServiceNow",
        path: "/servicenow",
        newTab: false,
        desc: "Enhance efficiency with comprehensive ServiceNow solutions for digital transformation.",
        imglink: "/assets/images/tech-services/tech-service-3.png",
      },
      {
        id: 205,
        title: "Open Source CRM",
        path: "/open-source-crm",
        newTab: false,
        desc: "Streamline sales, marketing, and customer service with cost-effective Open Source CRM solutions tailored for small businesses",
        imglink: "/assets/images/tech-services/tech-service-4.png",
      },
      {
        id: 206,
        title: "Hubspot CRM",
        path: "/hubspot-crm",
        newTab: false,
        desc: "Optimize HubSpot for success in marketing, sales, and service.",
        imglink: "/assets/images/tech-services/tech-service-5.png",
      },
      // {
      //   id: 207,
      //   title: "Excel CRM-Atom",
      //   path: "/excel-crm-atom",
      //   newTab: false,
      //   desc: "Simplify CRM with Atom, an Excel-based solution for SMBs.",
      //   imglink: "/assets/images/tech-services/tech-service-6.png",
      // },
      {
        id: 208,
        title: "MuleSoft",
        path: "/mulesoft",
        newTab: false,
        desc: "Connect data effortlessly with expert MuleSoft integration services.",
        imglink: "/assets/images/tech-services/tech-service-7.png",
      },
      {
        id: 209,
        title: "Marketo",
        path: "/marketo",
        newTab: false,
        desc: "Transform your business with strategic Salesforce CRM solutions.",
        imglink: "/assets/images/tech-services/tech-service-8.png",
      },
      {
        id: 203,
        title: "Customer Data Optimization & Cleanup",
        path: "/customer-data-optimization-and-cleanup",
        newTab: false,
        desc: "Simplify CRM with Atom, an Excel-based solution for SMBs.",
        imglink: "/assets/images/tech-services/tech-service-9.png",
      },
      // {
      //   id: 201,
      //   title: "E-Commerce & Development",
      //   path: "/e-commerce-and-development",
      //   newTab: false,
      //   desc: "Elevate your digital presence with our e-commerce and custom software solutions.",
      //   imglink: "/assets/images/tech-services/tech-service-10.png",
      // },
    ],
  },
  {
    id: 3,
    title: "Innovations",
    path: "/innovations",
    newTab: false,
    submenu: [
      {
        id: 301,
        title: "CRM AI-Elements",
        path: "/crm-ai-elements",
        newTab: false,
        desc: "Harness AI to redefine customer interactions with smarter, data-driven CRM capabilities.",
        imglink: "/assets/images/innovations/crm-ai.png",
      },
      {
        id: 302,
        title: "Excel CRM – Atom",
        path: "/excel-crm-atom",
        newTab: false,
        desc: "Simplify CRM with Atom, an Excel-based solution for SMBs.",
        imglink: "/assets/images/innovations/crm-excel.png",
      },
      {
        id: 303,
        title: "Salesman",
        path: "/salesman",
        newTab: false,
        desc: "Empower sales teams with intelligent, ML-driven product recommendations for seamless upselling and cross-selling",
        imglink: "/assets/images/innovations/sales and marketing alignment.png",
      },
      {
        id: 304,
        title: "SimCase",
        path: "/simcase",
        newTab: false,
        desc: "Centralize customer communication channels for actionable insights and enhanced customer service strategies.",
        imglink: "/assets/images/innovations/simcase.png",
      },
    ],
  },
  {
    id: 4,
    title: "Case Studies",
    path: "/case-studies",
    newTab: false,
  },
  {
    id: 5,
    title: "About Us",
    path: "/about-us",
    newTab: false,
    submenu: [
      {
        id: 501,
        title: "Who We Are",
        path: "/about-us",
        newTab: false,
      },
      {
        id: 502,
        title: "Our Team",
        path: "/our-team",
        newTab: false,
      },
      {
        id: 503,
        title: "CRM Insights",
        path: "https://vegacompass.medium.com/",
        newTab: true,
      },
    ],
  },
  // {
  //   id: 6,
  //   title: "Our Team",
  //   path: "/our-team",
  //   newTab: false,
  // },
];
export default menuData;
